apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-challenge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/G-03-XBrain-Phase-2/huypp-aws-accelerator-p2.git
    path: cloud/w9/challenge/k8s-api
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-challenge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
