apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: verify-ghcr-huypp
spec:
  images:
  - glob: "ghcr.io/huypp/w10-api*"
  authorities:
  - key:
      data: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+gsK40yFyTvi127a0zgioCxmrR2F\nkcv9Tyy7qk8EmVv/+fGlr4tEvVvMgpADfvP7aY083+xSSFQt8EuUsVcOLA==\n-----END PUBLIC KEY-----\n"
